Repository ucsb-cs156-m23/proj-happycows-m23-10am-1, pull requests merged in 2023-08, with the labels that each got.

#15 es - Fix schedule timezone bug
  src/main/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobs.java
  src/main/resources/application.properties
Labels: 5

#18 Hao - add back button and test for it for leaderboard
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 10

#30 Hao Added title animation to the home page
  frontend/src/main/components/css/HomePageTitle.css
  frontend/src/main/pages/HomePage.js
Labels: Has Team Member CR

#34 Implementation of Common Stats Recording & Endpoint
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonStats.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobFactory.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobs.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonStatsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthService.java
  src/main/resources/application-development.properties
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobsTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthServiceTest.java
Labels: Has Team Member CR

#24 Ziyang - Add CommonsStats entity and CommonsStats Repository
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonStats.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonsStats.java
Labels: FIXME-See CR

#35 Zixiao Jin backend for paged profits created
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
Labels: Has Team Member CR

#37 Ethan - Add capacity per user
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: Has Team Member CR
